### ISSUE TITLE
Add `range` support for ArrayValue.

### ISSUE THREAD

**Issue by skorokithakis** [icholy/vedis#2]
Currently, `ArrayValue` supports a `Next()` method, but it would be very useful if we could just do `for value := range arrayval`. Apparently, this can be implemented with an iterator protocol:

http://www.golangpatterns.info/object-oriented/iterators

**Comment by skorokithakis** [comment]
This seems to do the trick:

```
func (a *ArrayValue) Iter() <-chan *Value {
    ch := make(chan *Value)
    go func() {
        for i := 0; i < a.Count(); i++ {
            ch <- a.Next()
        }
        close(ch)
    }()
    return ch
}
```

**Comment by icholy** [comment]
I'd be more inclined to add a `Do` method

``` go
func (a *ArrayValue) Do(f func(*Value) error) error {
    l := a.Count()
    for i := 0; i < l; i++ {
        if err := f(a.Index(i)); err != nil {
            return err
        }
    }
    return nil
}
```

**Comment by skorokithakis** [comment]
Hmm, that's the `map` part, and my use case is more the `reduce` part, but I ended up just adding the loop inline, so feel free to close this.

**Comment by icholy** [comment]
@skorokithakis id you're using `Next` you should just check for `nil` instead of using `Count`

``` go
for v := a.Next(); a != nil; v = a.Next() {
    // use value
}
```

**Comment by skorokithakis** [comment]
Oh, good call, thanks!
